### ISSUE TITLE
Make Batching Strategy configurable

### ISSUE THREAD

**Issue by mangat2022** [datastax-cda/s3-file-to-astra#1]
use environment variable for batching of messages.

**Comment by jdabello** [comment]
Fixed in commit [933d3a6](https://github.com/datastax-cda/s3-file-to-astra/commit/933d3a6d53990517b7c0519fcf1804fa51e22d13). Added Env Variables BATCHING_ENABLED and BATCHING_MAX_PUBLISH_DELAY_MS, and updated README.

**Comment by mangat2022** [comment]
thank you @jdabello
